### ISSUE TITLE
Migrate convertBoolean() calls to use prepareParameters()

### ISSUE THREAD

**Issue by sprak3000** [Traackr/traackr-api-php#29]
Porting over suggestion from @rramaiah  

We already have a prepareParameters() flag that iterates over any found parameters and massages true / false into the strings “true” / ”false”. So, I propose we rely on `prepareParameters()` and strip out all of the older explicit `convertBool()` code that looks like this:

```
$p['enable_country_aggregation'] = $inf->convertBool($p, 'enable_country_aggregation');
```

**Comment by dchancogne** [comment]
Sounds good to me. If I remember correctly the original intent was to not have `prepareParameters` do too much black magic. But I think it's fine to simplify here.
